# -*- coding: utf-8 -*-
"""fase_1a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10iEWMv4ChhGnWreccodL61XfY0oomKQU

Os dados foram baixados do seguinte link disponibilizado no PDF do desafio -> https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data?resource=download
"""

#Importe dos dados

import pandas as pd

df = pd.read_csv("/data.csv")

#Verificando o tamanho da base e a dimencionalidade
df.shape

#Verificando se alguma coluna possui dados nulos ou faltntes
df.isnull().sum()

df.columns

#Todos os valores da Coluna Unnamed: 32 são nulos, portanto a coluna será excluída
df = df.drop("Unnamed: 32", axis=1)

#Removendo colunas que não são necessárias
df = df.drop("id", axis=1)

#Verificando se a coluna realmente foi excluída
df.columns

#Verificando quais são os tipos de dados na base
df.info()

#Verificando quais valores existem para a única variável que é OBJECT
df["diagnosis"].value_counts()

#Verificando a distribuição desses dados em %
df["diagnosis"].value_counts(normalize=True) * 100

#Transformando a variável vategórica em Numérica
df["diagnosis"] = df["diagnosis"].map({"B": 0, "M": 1})

#Verificando as estatísticas completas
df.describe()

#Verificando a distribuição entre Diagnosticos positivos e negativos
import matplotlib.pyplot as plt
df["diagnosis"].value_counts().sort_index().plot(kind="bar")
plt.xticks([0,1], ["Benigno", "Maligno"])
plt.title("Distribuição do Diagnóstico")
plt.show()

#Matriz de Correlação

plt.figure(figsize=(12,8))
sns.heatmap(corr, cmap="coolwarm", linewidths=0.5)
plt.title("Matriz de Correlação")
plt.show()

"""Na matriz de correlação, podemos observar uma correlação positiva (tons de vermelho escuro) entre características de tamanho, como radius, perimeter e area."""

#Verificando a correlação das demais colunas dos dados com o Diagnóstico Final
import seaborn as sns

corr = df.corr(numeric_only=True)

plt.figure(figsize=(10,6))
sns.heatmap(corr[["diagnosis"]].sort_values(by="diagnosis", ascending=False),
            annot=True, cmap="coolwarm")
plt.title("Correlação com Diagnóstico")
plt.show()

"""Mesmo que, como a professora comentou na aula, que a correlção dos dados não necessáriamente significa causalidade, podemos observar no mapa da calor que as variáveis com maior correlação (> 0.70) com a variável diagnóstico (que no caso consiste na mais importante na análise desses dados) são as seguintes:


*   concave points_worst (0.79)
*   perimeter_worst (0.78)
*   Concave_points_mean (0,78)
*   radius_worst (0.78)
*   perimeter_mean (0.74)
*   area_worst (0.73)
*   radius_mena (0.73)
*   area_mean (0.71)








"""

#Analisando a variável radius_mean
df.boxplot(column="radius_mean", by="diagnosis")
plt.xticks([1,2], ["Benigno", "Maligno"])
plt.title("Radius Mean por Diagnóstico")
plt.suptitle("")
plt.show()

"""os casos classificados como malignos, podemos observar que os valores de radius_mean tendem a ser maiores quando comparados aos casos benignos. Além disso, podemos perceber uma maior dispersão dos dados na classe maligna, indicando assim uma maior variabilidade desse atributo nesse grupo.

Nas duas classes (benigna e maligna), existem a presença de outliers, que são representados pelos pontos fora dos limites do boxplot, o que sugere a existência de alguns valores extremos nos dois tipos de diagnósticos.

Sendo assim, o atributo radius_mean apresenta um bom potencial de discriminação entre os diagnósticos, podendo ser considerado uma variável relevante para modelos de classificação.

"""

#Analisando a variável area_mean
df.boxplot(column="area_mean", by="diagnosis")

"""Analisando o gráfico, podemos verificar que a variável area_mean é  discriminante para o diagnóstico. Os diagnosticos do tipo 1 (Malígno) apresentam áreas médias maiores e com maior variação interna do que os do grupo 0 (Benígno). Os dois grupos também possuem a presença de outliers superiores."""

#Verificando o tamanho do tumor -> radius_mean
df.groupby("diagnosis")[["radius_mean", "area_mean", "texture_mean"]].mean().plot(kind="bar")
plt.xticks([0,1], ["Benigno", "Maligno"], rotation=0)
plt.title("Médias por Diagnóstico")
plt.show()

"""Confirmando o que foi visto no boxplot, a média da área dos tumores classificados como Maligno ( aprox. 980) é mais do que o dobro da média dos tumores Benignos (aprox. 460)"""

#Analisando de forma separada as 3 classes de médias
df.groupby("diagnosis")[["radius_mean", "area_mean", "texture_mean"]].mean().plot(kind="bar", subplots=True, layout=(1, 3), figsize=(12, 4))
plt.tight_layout()
plt.show()

"""A análise das médias nos permite observar que tumores malignos (1) são bem maiores e mais irregulares do que os benignos (0). A variável area_mean é o indicador mais impactante, dobrando de tamanho no diagnóstico maligno, e também há um aumento de 40% em radius_mean. A textura (texture_mean) também é maior no grupo maligno, embora apresente uma diferença menor (20%). Essas 3 classes de médias são características físicas e visuais dos tumores, e analisando podemos afimar que são discriminante para a separação das classes."""

#Histograma para a análise do Radius Mean
df["radius_mean"].hist(bins=30)
plt.title("Distribuição do Radius Mean")
plt.show()

"""Existe uma maior concentração de tumores na faixa entre 11 e 14, o que sugere que raios menores são mais frequentes.

Modelos escolhidos para a classificação: Random Forest e Regressão Logística
"""

from sklearn.preprocessing import StandardScaler

# Inicializa o padronizador, importante para a Regressão Logística
scaler = StandardScaler()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Remoção da coluna alvo
X = df.drop(columns=["diagnosis"])

# Armazenando em y o alvo
y = df["diagnosis"]

# Separação da base entre treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

# Ajusta e transforma os dados de treino, e APENAS transforma os de teste
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Treino: {X_train_scaled.shape[0]}")
print(f"Teste: {X_test_scaled.shape[0]}")

"""Foi adicionado a estratégia de amostragem estratificada (stratify=y), para que seja garantido que a proporção original de tumores benignos e malignos fosse mantida em ambas as partições."""

# Inicialização da Random Forest
modelo_rf = RandomForestClassifier(n_estimators=100, random_state=42, class_weight="balanced")

# Treinamento da Random Forest com os dados escalonados
modelo_rf.fit(X_train_scaled, y_train)

#Utilizando o modelo para Predição
y_pred = modelo_rf.predict(X_test_scaled)

#Avaliando a acurácia do Modelo
acuracia = accuracy_score(y_test, y_pred)
print(f"Acurácia: {acuracia * 100:.2f}%\n")

"""Apesar da acurácia ter um valor excelente, para o contexto é necessário avaliar outras métricas. Abaixo está o relatório."""

print(classification_report(y_test, y_pred, target_names=["Benigno", "Maligno"]))

"""Olhando para o Recall (Sensibilidade) da Classe de Maligno (93%), que é a métrica mais importante do cenário pois ela mede a capacidade do modelo de encontrar as pacientes doentes, verificamos que temos o valor de 0.93 indica que de 42 pacientes com tumores malignos, o modelo identificou 39 e deixou passar 3 (Falsos Negativos).

"""

#Avaliando melhor falsos NEGATIVOS e falsos POSITIVOS com a Matriz de Confusão
plt.figure(figsize=(6, 4))
cm = confusion_matrix(y_test, y_pred)

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="RdPu",
    xticklabels=["Benigno", "Maligno"],
    yticklabels=["Benigno", "Maligno"]
)

plt.ylabel('Realidade')
plt.xlabel('Previsão do Modelo')
plt.title('Matriz de Confusão - Random Forest')
plt.show()

"""Analisando a matriz de confusão, podemos observar 3 falsos positivos, quando o modelo classificou como tumor benigno, mas no entanto consistia em 3 tumores malignos."""

# Importância das Variáveis
importancias = modelo_rf.feature_importances_

df_importancia = pd.DataFrame({'Variável': X.columns, 'Importância': importancias})
df_importancia = df_importancia.sort_values(by='Importância', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x='Importância', y='Variável', data=df_importancia.head(10), hue='Variável', legend=False, palette='viridis')

plt.title('Variáveis Mais Importantes para o Diagnóstico')
plt.xlabel('Nível de Importância')
plt.ylabel('Atributo do Tumor')
plt.show()

"""O Feature Importance mostra que a variável area_worst é o fator mais determinante para o modelo,com mais de 15% de impacto, ou seja, o extremo do nódulo é o principal sinal de malignidade. Nas métricas de contorno e irregularidade como concave points_worst e perimeter_worst, somam mais de 23% da tomada de decisão. Podemos dizer que o algoritmo priorizou as variáveis de pior cenário (_worst) em vez das médias (_mean), bouscando focar na região mais agressiva da lesão para garantir um diagnóstico preciso."""

#Utilização da Técnica SHAP

import shap

explainer = shap.TreeExplainer(modelo_rf)
shap_values_obj = explainer(X_test_scaled)
shap.summary_plot(shap_values_obj[:, :, 1], X_test_scaled, feature_names=X.columns)

"""O gráfico SHAP indica que valores altos de características ligadas ao tamanho e à irregularidade do tumor, como já destacado e descutido antes, como concave points_worst e area_worst, possuem forte impacto positivo no SHAP value, empurrando a previsão na direção do diagnóstico Maligno.



Os valores baixos (pontos azuis) dessas mesmas variáveis agrupam-se à esquerda do eixo zero, correlacionando-se diretamente a previsões de tumores Benignos. Dessa forma, podemos notar que as variáveis associadas ao erro padrão (_se) mostram-se mais concentradas em torno do zero, indicando menor poder de decisão individual. Ou seja, podemos concluir que quanto maiores e mais côncavos forem os tumores, maior será o risco estimado de malignidade.

"""

#Regressão Logística

from sklearn.linear_model import LogisticRegression

modelo_lr = LogisticRegression(class_weight="balanced", random_state=42, max_iter=1000)
modelo_lr.fit(X_train_scaled, y_train)

#Predição
y_pred_lr = modelo_lr.predict(X_test_scaled)

#Avaliação dos Resultados
acuracia_lr = accuracy_score(y_test, y_pred_lr)
print(f"Acurácia Regressão Logística: {acuracia_lr * 100:.2f}%\n")
print(classification_report(y_test, y_pred_lr, target_names=["Benigno", "Maligno"]))

#Visualização dos resultados

#Combinação linear para as 114 pacientes do teste
scores = modelo_lr.decision_function(X_test_scaled)
probabilidades = modelo_lr.predict_proba(X_test_scaled)[:, 1]

#Gráfico
x_curva = np.linspace(scores.min() - 1, scores.max() + 1, 300)
y_curva = 1 / (1 + np.exp(-x_curva))
plt.figure(figsize=(10, 6))
plt.plot(x_curva, y_curva, color='purple', linestyle=':', alpha=0.5, label='Curva Sigmoide Teórica')

plt.scatter(scores[y_test == 0], probabilidades[y_test == 0],
            color='blue', alpha=0.7, edgecolors='k', label='Pacientes Benigno (72)')
plt.scatter(scores[y_test == 1], probabilidades[y_test == 1],
            color='crimson', alpha=0.7, edgecolors='k', label='Pacientes Maligno (42)')

# Linha do limiar de decisão de 0.5 (onde o modelo divide as classes)
plt.axhline(y=0.5, color='gray', linestyle='--', alpha=0.7, label='Limiar de Decisão (0.5)')
plt.axvline(x=0, color='gray', linestyle='--', alpha=0.3)

# Customização
plt.title('Regressão Logística Aplicada aos Dados do Teste', fontsize=14, pad=15)
plt.xlabel('Score do Tumor', fontsize=11)
plt.ylabel('Probabilidade de Malignidade', fontsize=11)
plt.yticks([0, 0.25, 0.5, 0.75, 1.0], ['0 (Benigno)', '0.25', '0.50', '0.75', '1 (Maligno)'])

plt.grid(True, linestyle=':', alpha=0.5)
plt.legend(loc='upper left')
plt.show()

#Matriz de Confusão
plt.figure(figsize=(6, 4))
cm_lr = confusion_matrix(y_test, y_pred_lr)
sns.heatmap(cm_lr, annot=True, fmt="d", cmap="RdPu",
            xticklabels=["Benigno", "Maligno"],
            yticklabels=["Benigno", "Maligno"])
plt.ylabel('Realidade')
plt.xlabel('Previsão do Modelo')
plt.title('Matriz de Confusão - Regressão Logística')
plt.show()

"""Analisando a matriz de confusão, podemos dizer que Para tumores benignos, o algoritmo demonstrou altíssima eficácia ao acertar 71 dos 72 casos reais, resultando em um recall de 99%. No cenário crítico de malignidade, o modelo minimizou riscos graves ao capturar com sucesso 40 dos 42 tumores reais (recall de 95%). A margem de erro limitou-se a apenas 2 falsos negativos e 1 falso positivo. A Regressão Logística é Mais Segura, uma vez que o objetivo principal é minimizar os Falsos Negativos. A Regressão Logística identificou 40 dos 42 casos malignos (Recall de 95.24%), enquanto a Random Forest identificou 39. Sendo assim, podemos dizer que a Regressão Logística foi estatisticamente superior no quesito segurança."""

# Coleta dos coeficientes do modelo
coeficientes = modelo_lr.coef_[0]

# Ordenação do impacto das variáveis
df_coef = pd.DataFrame({'Variável': X.columns, 'Coeficiente': coeficientes})
df_coef = df_coef.sort_values(by='Coeficiente', ascending=False)

# 10 variáveis que mais empurram o diagnóstico para "Maligno"
plt.figure(figsize=(10, 6))
sns.barplot(x='Coeficiente', y='Variável', data=df_coef.head(10), hue='Variável', legend=False, palette='coolwarm')
plt.title('Top 10 Variáveis que Indicam Malignidade')
plt.xlabel('Peso do Coeficiente)')
plt.ylabel('Atributo do Tumor')
plt.show()

"""O gráfico de coeficientes da Regressão Logística nos mostra que a irregularidade e a variação estrutural do nódulo são os fatores mais determinantes para apontar a malignidade de um tumor. A variável texture_worst fica em primeiro lugar como o principal indicador de risco, seguida de perto por radius_se, evidenciando que uma textura muito áspera e alta oscilação no raio elevam drasticamente a probabilidade de câncer. Podemos notar também que há mais dos atributos do tipo _worst,  que prova que o modelo prioriza os piores cenários e as regiões mais agressivas da lesão em vez de médias gerais. Como todos os coeficientes são positivos, cada um desses dez fatores atua proporcionalmente, impulsionando o diagnóstico em direção à classe maligna.


"""

#MATRIZ DE CONCORDÂNCIA ENTRE OS MODELOS

# Gerar as probabilidades de previsão para a classe Maligno 1
prob_rf = modelo_rf.predict_proba(X_test_scaled)[:, 1]
prob_lr = modelo_lr.predict_proba(X_test_scaled)[:, 1]

# DataFrame de Validação Cruzada
df_validacao = pd.DataFrame({
    'Realidade': y_test.values,
    'Pred_RandomForest': y_pred,
    'Prob_RandomForest': prob_rf,
    'Pred_RegLogistica': y_pred_lr,
    'Prob_RegLogistica': prob_lr
})

# Identificação das discondâncias
df_discordancia = df_validacao[df_validacao['Pred_RandomForest'] != df_validacao['Pred_RegLogistica']].copy()
print(f"Total de casos no teste: {len(df_validacao)}")
print(f"Casos onde os modelos discordaram: {len(df_discordancia)}\n")


# Matriz de Concordância entre os Modelos
plt.figure(figsize=(6, 5))
cm_modelos = confusion_matrix(df_validacao['Pred_RandomForest'], df_validacao['Pred_RegLogistica'])
sns.heatmap(cm_modelos, annot=True, fmt="d", cmap="Greens",
            xticklabels=["Benigno (LR)", "Maligno (LR)"],
            yticklabels=["Benigno (RF)", "Maligno (RF)"])
plt.title("Matriz de Concordância: Random Forest vs Regressão Logística")
plt.xlabel("Previsões da Regressão Logística")
plt.ylabel("Previsões do Random Forest")
plt.show()

"""A matriz de concordância consiste em uma ferramenta para a validação de robustez. Os dois modelos utilizados empregam técnicas diferentes, a Regressão Logística utilizando a geometria linear e o Random Forest utilizando árvores de decisões, quando os dois modelos chegam na mesma conclusão sobre um caso, a confiabilidade do diagnóstico aumenta. A matriz serve como uma prova de que os modelos encontraram de fato um padrão biológico na base de dados, descartando a utilização de “chute” estatístico."""